<a href='https://aims-senegal.org/'> <img src='http://sn.nexteinstein.org/wp-content/uploads/sites/12/2016/07/aims_senegal.jpg' /></a>

In [ ]:
# run this cell first
import numpy as np



---



---



---



# Exercise A:




### 1- Construct a Ndarray  of shape (3, 2) filled with **8**, Then set element (0, 1) to 10, and element (1, 0) to 100

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 2- Create a 64-bit floating-point Ndarray of shape (6,) (six-element vector) filled with evenly-spaced values between 10 and 20. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 3- Create a vector with values ranging from 10 to 49

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 4- Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 5- Create a 10x10 array with random values and print the trace value and the mean values of each row

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 6- Create a Ndarray array of size (5, 5) with all **1** on the borders and all **0** in the inside


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 7- Create random vector of size 10 and replace the maximum value by 0

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 8- Normalize a 5x5 random matrix
Hint: subtract the mean and devide by the standard deviation

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

### 9- Create a random 5x2 matrix representing cartesian coordinates and print an array **"polar"** with same shape representing the converted polar coordinates.

Hints:

X represent the first column.

Y represent the second column.

Compute:

$$ R = \sqrt{X^2 + Y^2} $$

$$ T = \arctan{(Y, X)} $$


In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################


#your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################



---



---



---



### 10- Write a function that normalizes the columns of a matrix. It should compute the mean and standard deviation of each column, then subtract the mean and divide by the standard deviation for each element in the column. 

Example:
```
x = [[ 0,  30,  600],
     [ 1,  10,  200],
     [-1,  20,  400]]
```
- The first column has mean 0 and std 1
- The second column has mean 20 and std 10
- The third column has mean 400 and std 200

After normalizing the columns, the result should be:
```
y = [[ 0,  1,  1],
     [ 1, -1, -1],
     [-1,  0,  0]]
```

Your implementation should not use any loops; instead you should use reduction and broadcasting operations.

In [ ]:


################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def normalize_columns(x):

  # x: (input) Ndarray of shape (N, M) (don't modefy it: use copy())
  # y: (return) Ndarray of shape (N, M) normalized by the columns
  
  #your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [ ]:
x0 = np.array([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1.224744871391589, 1.224744871391589], [1.224744871391589, -1.224744871391589, -1.224744871391589], [-1.224744871391589, 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]



---



---



---



### 11- creates a function that returns a matrix of **one-hot vectors** from a list of Python integers. A one-hot vector for an integer $n$ is a vector that has a one in its $n$th slot, and zeros in all other slots. One-hot vectors are commonly used to represent categorical variables in machine learning models.

### For example, given a list `[1, 4, 3, 2]` of integers, your function should produce the tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

### Here the first row corresponds to the first element of the list: it has a one at index 1, and zeros at all other indices. The second row corresponds to the second element of the list: it has a one at index 4, and zeros at all other indices. The other rows follow the same pattern. 

In [ ]:
################################################################################
#                              START OF YOUR CODE                                #
################################################################################
def make_one_hot(x):

  #x: (input) A list of n ints
  
  #your code should be here
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

Run the following cell to check your implementation, you must see 'all checks pass!' message

In [ ]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')



---



---



---



# Exercise B:

### Maximum Likelihood
Find the maximum likelihood estimation of parameters $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N
$$

Steps to follow:


1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Compute the maximum likelihood estimation of parameters $\boldsymbol\theta$ following the equation and assign it to a variable called **theta**

$$
\boldsymbol\theta = (\boldsymbol X^T\boldsymbol X)^{-1}\boldsymbol X^T\boldsymbol y\in\mathbb{R}^D
$$

4. print the value of **theta**

Hint: check the inverse method from the linear algebra module in Numpy

In [ ]:
################################################################################
# TODO: Compute the maximum likelihood estimation of parameters theta
#       following the equation
################################################################################


#your code should be here

 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################



---



---



---



# Exercise B:

### The Log Likelihood

Find the log likelihood estimation for input X, label y, parameterized by $\boldsymbol\theta$.

Given:

$$
\boldsymbol X \in\mathbb{R}^{N\times D} \quad \boldsymbol y  \in\mathbb{R}^N \quad \boldsymbol \theta  \in\mathbb{R}^D
$$

steps to follow:

1.   Initialize Ndarray **X** from a normal distribution with shapes: N = 10 and D = 5.
2.   Initialize Ndarray **y** with all ones with shape N = 10 and reshape it to have the shape (N, 1).
3.   Initialize Ndarray **theta** randomly with shape D = 5 and reshape it to have the shape (D, 1).
4.   Compute the the probability of a all data points $(\boldsymbol x, y)$ being of class 1, given by

$$p(y = 1 | \boldsymbol X, \boldsymbol\theta) = 1.0/(1.0+\exp(- \boldsymbol X \boldsymbol \theta))$$

5. compute the log Likelihood, given by:
$$\log p(\boldsymbol y|\boldsymbol X, \boldsymbol\theta) = \sum_i y_i * \log (p(y = 1 | \boldsymbol x, \boldsymbol\theta) + (1 - y_i) * \log ( 1 - p(y = 1 | \boldsymbol x, \boldsymbol\theta))$$

6. print the log Likelihood

In [ ]:
################################################################################
# TODO: Compute the log likelihood 
#    
################################################################################


#your code should be here

X = np.random.randn(10, 5)
y = np.ones((10,1))
theta = np.random.random((5, 1))

p = 1.0/(1 + np.exp(-X @ theta))
L = np.sum(y*np.log(p) + (1 - y)*np.log(1 - p))

print(L)
 
################################################################################
#                              END OF YOUR CODE                                #
################################################################################

In [ ]:
import numpy as np

In [ ]:
A = np.arange(9).reshape(3,3)

B = [2, 1, 0]

print(A[np.arange(4), B])

IndexError: ignored

In [ ]:
B

array([[1, 2, 2, 0],
       [3, 4, 1, 2]])


```
A = [[1  2  2  3],
     [4  5  0  1]]
```

```
B = [[9  10]
    [14 15]]
```
### Which of the following options will return B: